### ISSUE TITLE
Cannot use Write node from node-red (thethingbox)

### ISSUE THREAD

**Issue by tvillingett** [tzapu/node-red-contrib-blynk#1]
I cannot get the write module to send values from node-red, is there any special format on the payload?

**Comment by tzapu** [comment]
hi, do the event nodes work? do you get anything in debug or in the console?
no special format, whatever is in payload gets sent, try to send a short (4char) string and display it on a value display in the app

**Comment by tvillingett** [comment]
Hi, now I started from scratch and got it to write to the Blynk app. I think the problem was I was using a local Blynk server and was expecting it to work, but I guess you need to change the module code to be able to choose some other server than the Blynk "cloud" server.
