### ISSUE TITLE
Problem each time I when I press deploy in node-red    ( ssl connection )

### ISSUE THREAD

**Issue by Toshibass** [tzapu/node-red-contrib-blynk#10]
Regarding issue #3 (Problem each time I when I press deploy in node-red) Your fix appeared to work as I didn't get the warning: possible EventEmitter memory leak detected, however I now tested ssl connection and each time I deploy my flow which uses 28 blynk nodes, I get 

Trace
    at addListener (events.js:179:15)
    at /home/pi/.node-red/node_modules/node-red-contrib-blynk/node_modules/blynk-library/blynk.js:487:17
    at Socket.<anonymous> (/home/pi/.node-red/node_modules/node-red-contrib-blynk/node_modules/blynk-library/blynk-node.js:51:7)
    at Socket.g (events.js:199:16)
    at Socket.emit (events.js:129:20)
    at TCPConnectWrap.afterConnect [as oncomplete](net.js:1001:10)
(node) warning: possible EventEmitter memory leak detected. 11 end listeners added. Use emitter.setMaxListeners() to increase limit.

So it seams you need to do a similar fix with a higher value in max event listeners on ssl connections

regards Toshi

**Comment by tzapu** [comment]
that s an error in blynk library js, nothing i can do on this side.
this might also be fixed within my current pull request to them
https://github.com/vshymanskyy/blynk-library-js/pull/8

will close here
cheers
