### ISSUE TITLE
node-red log

### ISSUE THREAD

**Issue by Toshibass** [tzapu/node-red-contrib-blynk#13]
Hi tzapu

Regarding node_red-contrib-blink logging, is there anyway to suppress what is logged to the node-red-log, for example I am currently using 35 nodes and the node-red log has a line "input on virtual write" 472,414 times in the last 12 hours in reality it useless info: I would like to see in there when blynk gets authorised and connected etc (with time stamps) and if something goes wrong but a file full of "input on virtual write" with no indication of time/date is pretty un-helpfully and over a week the file will be huge not to mention the stress on the sd card of all these writes.
Thanks as always for you fast responses and commitment despite the teething problems these nodes are superb and in my view a much better/flexible way to use the blynk app. 

Regards Toshi

**Comment by tzapu** [comment]
Hi Toshi, thanks for your kind words. 
I'll push an update in a few minutes that is inspired from some better behaving plugins via logging.
Basically, most stuff will be omitted when run normally, but you can add the verbose `-v` flag when starting node-red to get full debug.

**Comment by tzapu** [comment]
addressed in node-red-contrib-blynk@0.0.14
if you see other way of improving it, please let me know
