### ISSUE TITLE
An unused connection still tries to connect

### ISSUE THREAD

**Issue by tvillingett** [tzapu/node-red-contrib-blynk#14]
If I have defined a Blynk connection to a server that is not used, it still tries to connect:
Connecting to TCP: 127.0.0.1 8441
Error ECONNREFUSED

And it gives messages in the log ( http://thethingbox.local/console.txt )

**Comment by tvillingett** [comment]
I dissapered when i erased the definition, I only used the cloud server at this moment.

**Comment by tzapu** [comment]
the server node gets initialised if it is added so that would be the expected behaviour as it is.

i am not sure if i can obtain the information that the server is used or not at the time of intialisation so i skip it ...

**Comment by tvillingett** [comment]
Ok, I guess that is the best behaviour, also since the server could be temporary out of reach because of network or other issues, it is good to continue to try to access it.
As long as the error doesn't make any excessive cpu load or other bad things.
