### ISSUE TITLE
Not reconnecting.

### ISSUE THREAD

**Issue by scargill** [tzapu/node-red-contrib-blynk#19]
Got latest Node-Red updates yesterday and latest BLYNK node updated. All was fine until this evening - the App said my generic board was not connected. Sure enough I looked into Node-Red and all the BLINK uses were disconnected.  A reset of Node-Red and they all came back on. I can only assume it is still NOT recovering from temporary disconnected local Blynk server. 

Happy to do any tests.

**Comment by tzapu** [comment]
hi, if you have it handy, it would be good to see the server disconnect part of the node red log

**Comment by tzapu** [comment]
already a couple of issues opened for this
