### ISSUE TITLE
Led,s broken with latest iOS blynk update!

### ISSUE THREAD

**Issue by Toshibass** [tzapu/node-red-contrib-blynk#23]
Just updated blynk app for iOS everything appears to work except LED's no chance to track what's happening yet to late tonight.

**Comment by doom369** [comment]
iOS LED logic was wrong. Now you have yo send 255 in order to make it light instead of 1. As it was before.

**Comment by doom369** [comment]
@tzapu I think you may close it =)

**Comment by tzapu** [comment]
thanks @doom369 
you have a great team, now even offering third party support :D, so looking forward to see what you come up with in time and i am so glad i backed blynk on KS
thanks for all your work

**Comment by doom369** [comment]
Thank you!
