### ISSUE TITLE
using this node to read values

### ISSUE THREAD

**Issue by scropion86** [tzapu/node-red-contrib-blynk#24]
hello,

can this node allow me to read the values of may gauges .
as my project has two gauges for temperature and Humidity.
i add this node to my node-red and add my running dashboard Token and assign it to read V4 and V5
but i am getting this from debug 

```
msg : Object
{ "pin": "4", "payload": "4", "_msgid": "f3254624.0cdab8" }
```

also i get that my device not in network notification once node-red connected to the system and the connection return after some time.
any idea can help.

**Comment by tzapu** [comment]
this replaces an actual device, so this actually reads and feeds data to your mobile device's Blynk app.

as far as i know you can only write to your Blynk gauges, not read

**Comment by doom369** [comment]
@tzapu you can with SYNC command (was introduced recently). I'm finishing example for websockets at the moment. Will publish update in few hours. This javascript byte manipulations are such a pain.

**Comment by tzapu** [comment]
i m a firm believer javascript is a pain at all times...

thanks for letting me know, i will look into all this at length

**Comment by tzapu** [comment]
btw, thinking about it, with a websockets interface, you might not even need MQTT to interact with node-red at least... 
will try to play with it as much as possible and see if it can get it working as i'd see it used

**Comment by doom369** [comment]
node-red supports web sockets?

**Comment by tzapu** [comment]
indeed it does
https://www.dropbox.com/s/rgyoethzqyn941r/Screenshot%202016-01-18%2016.52.13.png?dl=0

**Comment by tzapu** [comment]
will blynk.cc support websockets as well?

**Comment by doom369** [comment]
You mean cloud.blynk.cc? Yes, but only after we will test it well. Because load on Blynk is high enough and I afraid to add not well tested features =).

**Comment by tzapu** [comment]
as long as it s planned in the short to medium term, i think is good enough :+1: 

having a local server is so fast i don t think i d go back to blynk.cc but, to get started it sure is a million times easier just to use your cloud offering

**Comment by doom369** [comment]
@tzapu released. https://github.com/blynkkk/blynk-server/releases/tag/v0.12.4

Also please have a look into simple example I made. It should be good starting point for you. Let me know If you need something else.

**Comment by doom369** [comment]
@tzapu regarding speed - the current problem is - we hosted only in USA. Geo servers will be provided in few months. After that speed will be increased dramatically.

**Comment by tzapu** [comment]
hi, was able to connect and blynk a button just fine from your sample. exciting times ahead :)

regarding connection and timeout management, currently set at 15 seconds, do you have any idea what an acceptable usage pattern will be when this eventually makes it in cloud.blynk.cc ?

15 seconds timout, and keep alive ping every 10? or ... i don t know... just trying to think which way to take this 

cheers
alex

**Comment by tzapu** [comment]
as i mentioned, i was able to use example just fine.
unfortunatelly, it doesn t really work together well with the node-red websockets connector, you don t have a reconnect event to send login again, and so on

however, i am thinking of taking the websockets node and modifying them to fit blynk as a new set of nodes, that should still be more reliable and faster to update rather than waiting on server/js lib/my lib chain to do anything...

still pondering. do let me know what an acceptable connection and keep alive pattern would be for the future cloud.blynk.cc integration as well

**Comment by doom369** [comment]
@tzapu we use pings on hardware. Every 5 sec. I added timer for example page.

> you don t have a reconnect event to send login again

This could be easily done on javascript. This example is just for demonstration purposes. @vshymanskyy currently working on integration of Electric Imp. via WebSockets. Maybe he will do all this =).

Also pls take latest build again, it has small bug fix for websockets.

**Comment by tzapu** [comment]
;) thanks, will do

**Comment by tzapu** [comment]
@scropion86 the sync feature is not added to the contrib.
currently i am playing with the websockets version, which might or might not replace this one, will have to see
cheers

**Comment by scropion86** [comment]
ok i will wait for that , but what about the normal restfull API that Dmitri said about.
i can read any pin ether D pin or V pin using it with GET request. but never get a replay
back for changing the value of pins using PUT request .
any idea 

see the last replay on this post http://community.blynk.cc/t/ifttt-and-blynk-questions/3573/11
