### ISSUE TITLE
ios-blynk-app-failing

### ISSUE THREAD

**Issue by Toshibass** [tzapu/node-red-contrib-blynk#25]
Hi Tzapu are you seeing same issue as this on your setup   ?  http://community.blynk.cc/t/ios-blynk-app-failing/4783

**Comment by tzapu** [comment]
thanks for letting me know, let s discuss it there

**Comment by Toshibass** [comment]
This issue has now been resolved, see    http://community.blynk.cc/t/ios-blynk-app-failing/4783
