### ISSUE TITLE
Problem with write event node

### ISSUE THREAD

**Issue by Toshibass** [tzapu/node-red-contrib-blynk#4]
Hi (Thanks, by the way for resolving #3 works nice now) however I came across another problem, if I use the write node to toggle (send 1 then 0) to a LED on a virtual pin say v10 it works fine, if I then replace the LED with a BUTTON on v10 I expected the button to toggle On then Off but it doesn't work, am I missing something ? 
Toshi

**Comment by tzapu** [comment]
no probs. 
what you are missing is something we all are really. the blynk framework/service/app does not support toggling buttons yet it seems

**Comment by tzapu** [comment]
i ll close this as they have it under consideration
