### ISSUE TITLE
Node-Red  crash

### ISSUE THREAD

**Issue by Toshibass** [tzapu/node-red-contrib-blynk#5]
I had deployed a number of blynk nodes in node-red and they were all working fine then BOOM node-red crashed I have no idea why but when I try to restart node-red now I get the same error 
# Welcome to Node-RED

20 Oct 11:07:24 - [info] Node-RED version: v0.11.2
20 Oct 11:07:24 - [info] Node.js  version: v0.12.7
20 Oct 11:07:24 - [info] Loading palette nodes
20 Oct 11:07:33 - [info] Settings file  : /usr/lib/node_modules/node-red/settings.js
20 Oct 11:07:33 - [info] User directory : /home/pi/.node-red
20 Oct 11:07:33 - [info] Flows file : /home/pi/.node-red/new_file.json
20 Oct 11:07:33 - [info] Server now running at http://127.0.0.1:1880/
20 Oct 11:07:33 - [info] Starting flows
blynk server init f7669ec9296b4ff08b88220a4464df61
New Blynk connection with key f7669ec9296b4ff08b88220a4464df61 false
OnOff mode
Connecting to TCP: cloud.blynk.cc 8442
blynk virtual pin write init 5
20 Oct 11:07:35 - [info] Started flows
20 Oct 11:07:35 - [red] Uncaught Exception:
20 Oct 11:07:35 - Error: getaddrinfo ENOTFOUND cloud.blynk.cc
    at errnoException (dns.js:44:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete](dns.js:94:26)

The only way I can get node-red to run is by using   node-red new_file.json     to start a new blank canvas, if I then use a blynk node it crashes with above error, so now I cannot use any blynk nodes.

**Comment by tzapu** [comment]
hi, that looks like it can t connect to blynk server on that port...

i just tried and i can t connect either, maybe they are working on the server?

/edit i was able to connect with both ssl and non ssl, with a valid project token

will try updating libraries to see if anything new happened

**Comment by tzapu** [comment]
hi, works for me after all updates. the error you are getting seems to be in dns resolution, it can t find cloud.blynk.cc

can you ping it from that machine?

**Comment by Toshibass** [comment]
That is without ssl      key f7669ec9296b4ff08b88220a4464df61 false

I had not tried with ssl but I just did and node-red doesn't crash now however it doesn't connect ether so I tried after refreshing auth code same result....

New Blynk connection with key ...........bla bla.............. true
OnOff mode
Connecting to SSL: cloud.blynk.cc 8441
blynk virtual pin write init 5
20 Oct 11:57:34 - [info] Started flows
Connecting to SSL: cloud.blynk.cc 8441
Connecting to SSL: cloud.blynk.cc 8441
Connecting to SSL: cloud.blynk.cc 8441

with new auth code, if I turn ssl off and re-deploy, node-red crashes again with same error report

**Comment by Toshibass** [comment]
Yes I can ping the server in fact since the issue I have been implementing some mqtt nodes which connect to the same esp8236 and using the original auth key (before I changed it) and using the replacement auth key, they work fine, however if I open a new blank-canvas node-red session and use any of the Blynk nodes with ssl un-ticked node red still crashes immediately

20 Oct 18:05:16 - [info] Starting flows
blynk server init ......bla bla........
New Blynk connection with key  ......bla bla........ false
OnOff mode
Connecting to TCP: cloud.blynk.cc 8442
blynk virtual pin write init 5
20 Oct 18:05:16 - [info] Started flows
20 Oct 18:05:16 - [red] Uncaught Exception:
20 Oct 18:05:16 - Error: getaddrinfo ENOTFOUND cloud.blynk.cc
    at errnoException (dns.js:44:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete](dns.js:94:26)

 if I tick ssl I still cannot connect 

20 Oct 18:08:51 - [info] Starting flows
blynk server init ......bla bla........
New Blynk connection with key  ......bla bla........ true
OnOff mode
Connecting to SSL: cloud.blynk.cc 8441
blynk virtual pin write init 5
20 Oct 18:02:52 - [info] Started flows
Connecting to SSL: cloud.blynk.cc 8441
Connecting to SSL: cloud.blynk.cc 8441
Connecting to SSL: cloud.blynk.cc 8441

Suppose I could re-install the blynk nodes but that's not going help to find the problem and in any case shouldn't the error be handle properly so node-red doesn't crash, its quite traumatic as I have a lot of flows (nothing to do with blynk) and when it crashes its not possible to log on again to that session.

**Comment by tzapu** [comment]
yes, errors need to be handled better
i've actually got a couple of issues opened with them for exactly this
https://github.com/vshymanskyy/blynk-library-js/issues/5
https://github.com/vshymanskyy/blynk-library-js/issues/2

awaiting them to be implemented
i have updated https://github.com/vshymanskyy/blynk-library-js/ and noticed it s up to blynk-library@0.0.21 from 0.0.16 when i started on this. what version do you have installed?

**Comment by tzapu** [comment]
for reference, here s how i have it set to connect to the blynk official server
https://www.dropbox.com/s/qq4ip6zx9ikucv7/Screenshot%202015-10-20%2022.10.16.png?dl=0

**Comment by Toshibass** [comment]
my blynk lib is 0.1.9    15/10/2015   so like only 5 days old, but I will update tomorrow to see if it has any effect, as for the reference you posted as I said I didn't mess with ssl yet other than ticking that box, I guess KEY at the end of the Auth Token is something to do with certs ?

**Comment by tzapu** [comment]
no, that was just my obfuscation of the token :)
get the latest one of these as well https://github.com/vshymanskyy/blynk-library-js/ they seem to have versions in the 0.0.21 range of things, not 0.1.9

**Comment by Toshibass** [comment]
sorry my mistake should have said "my blynk lib is 0.0.19 15/10/2015" , anyway tried for latest 0.0.21  had to download zip file way because sudo npm install blynk-library still installs 0.0.19 tried a new node-red instance with a different auth code (this one is esp controlling relays in a extension lead and it works fine from blink ios) as soon as I deploy node red without ssl, red crashes and I get same error.

**Comment by Toshibass** [comment]
Having tried everything to trace this issue, this afternoon I ended up wiping my sd card and starting from scratch, clearly a big pain, but I had to do it, I found that it was not possible to install any nodes from whatever source so this issue broke node-red big style, I am going carry on using the blynk nodes in the hope that it doesn't happen again, or you come across a fix before it breaks again .

**Comment by tzapu** [comment]
i hope it doesn't happen again as well, i couldn't find anything on it
will leave this open for a bit to see it's stable or not

**Comment by tzapu** [comment]
added a pull request to blynk js library regarding this so at least it doesn t crash everything
https://github.com/vshymanskyy/blynk-library-js/pull/8
hopefully they will accept it
in the mean time you could use my fork of the library
