### ISSUE TITLE
Another uncaught error causing node-red crash

### ISSUE THREAD

**Issue by Toshibass** [tzapu/node-red-contrib-blynk#7]
input on virtual write
26 Oct 16:23:18 - [red] Uncaught Exception:
26 Oct 16:23:18 - Error: write EPIPE
    at exports._errnoException (util.js:746:11)
    at WriteWrap.afterWrite (net.js:775:14)

**Comment by tzapu** [comment]
hi, could you give me a sample node red flow(minimum viable to reproduce) and let me know what value you are sending?
cheers

**Comment by Toshibass** [comment]
Sorry not possible had about 30 nodes working at the time it crashed, restarted and it's been fine since, so no idea whitch caused the error, in reality I am only sending 0 1 and some sensor values nothing special, but thought I would add here to inform another uncaught error code.
