### ISSUE TITLE
LCD node

### ISSUE THREAD

**Issue by Toshibass** [tzapu/node-red-contrib-blynk#9]
Trying to use inject node (string) to send  lcd.print(0,0,"hello");  to write event node virtual pin 27 (LCD widget) but its not working.

Am I doing something wrong or is this element not available yet ,(if not, do you plan to implement ?)

Toshi

**Comment by tzapu** [comment]
hi, not available yet. it;s not in blynk js library. 
as soon as they make it available, i will add it as a node

i'd wish they d tackle the connection errors first though.
thanks

**Comment by tzapu** [comment]
https://github.com/vshymanskyy/blynk-library-js/issues/9
suggested there

**Comment by tzapu** [comment]
added LCD widget (advanced mode) in node-red-contrib-blynk@0.0.15
give it a test, update blynk-library as well

**Comment by Toshibass** [comment]
Hi Tzapu, I gave the LCD widget a quick test (thanks for working on this by the way)  ... blynk-library 0.0.23 , node-red-contrib-blynk 0.0.16 ,  iphone , new project with just inject node and lcd print node v-pin 1 , app active on Iphone, 

First of all what is correct syntax for sending a message ... if I send ...  lcd.print(0,0,"Hello from Node-Red") (the format detailed on the node  in the app) the blynk app on iphone crashes, however I found I can enter just Hello and that pops up on the lcd display clear-lcd also works but how to get msg to print at coordinates / second line?

There is an issue (although it goes on to work)... when I press deploy in  node-red I get ... "node-red-contrib-blynk:LCD Pin already in use" this also happens every time I connect another say inject node to the lcd-print node then deploy or disconnect a node that's already connected to the lcd-print node then deploy.

**Comment by tzapu** [comment]
see here 
https://github.com/tzapu/node-red-contrib-blynk/issues/17
